const List<String> kDepartmentOptions = [
  'General Department',
  'Engineering',
  'Support',
  'Supply Chain Management',
  'Management',
  'Design & Development',
  'Accounts',
  'Pre Sales',
  'Administration',
  'Production',
  'Sales',
  'Support Production And Project',
  'Projects',
  'IT',
  'HR',
  'Audit',
  'Support Production And Project',
  'Design & Development',
  'Sales - Defence',
  'International Business',
  'HR & Admin',
  'HR, IT, SCM & Admin',
  'Engineering & Production',
  'Solution Design-Ops',
];

const List<String> kResponsibleDepartmentOptions = [
  'Engineering',
  'Support',
  'Supply Chain Mgmt',
  'R&D',
  'Accounts',
  'Pre Sales',
  'Production',
  'Sales',
  'Support Production',
  'Projects',
  'IT',
  'HR',
  'Audit',
  'Operation',
];
